### ISSUE TITLE
Missing data.csv 

### ISSUE THREAD

**Issue by paduel** [bukosabino/streamlit-demo-financial-eda#1]
When trying to run the example it doesn't find the data.csv file. I used one of my own for testing, but it didn't match the format and I had to check the code to format the csv.

I thought you could include in the repository the data.csv file that you used to make it easier to test your development.

**Comment by bukosabino** [comment]
Hi @paduel ,

Sorry about this. Now it is fixed. Thank you for your time in testing the demo!
